
/* Drop Tables */

DROP TABLE IF EXISTS T_AM_WTL_PIP;
DROP TABLE IF EXISTS T_INEV_CND;
DROP TABLE IF EXISTS T_INEV_GRAD;
DROP TABLE IF EXISTS T_INEV_LYYY_REVISN;
DROP TABLE IF EXISTS T_INEV_WTL_PIP;
DROP TABLE IF EXISTS T_INEV_M;
DROP TABLE IF EXISTS T_INEV_WGHT;




/* Create Tables */

-- 자산 상수관로
CREATE TABLE T_AM_WTL_PIP
(
	-- 자산 일련번호
	ASST_SN INT NOT NULL,
	-- 관리번호
	FTR_IDN VARCHAR(20),
	-- 대블록 명
	LBLK_NM VARCHAR(200),
	-- 중블록 명
	MBLK_NM VARCHAR(200),
	-- 소블록 명
	SBLK_NM VARCHAR(200),
	-- 설치일
	INSTALL_YMD NUMERIC,
	-- 관종 코드
	MTRPIPE_CD VARCHAR(20),
	-- 관경
	PIP_DMTR NUMERIC,
	-- 관두께
	PIP_THKNS NUMERIC,
	-- 관길이
	PIP_LT NUMERIC,
	-- 최저 깊이
	LWET_DP NUMERIC,
	-- 최고 깊이
	TOP_DP NUMERIC,
	-- 토양 종류
	SOIL_KND VARCHAR(5),
	-- 전기 방식 값
	ELTR_MENS_VAL NUMERIC,
	-- 도로 유형
	ROAD_TY VARCHAR(5),
	CONSTRAINT pk_t_am_wtl_pip PRIMARY KEY (ASST_SN)
) WITHOUT OIDS;


-- 간접평가조건 : 간접평가조건
CREATE TABLE T_INEV_CND
(
	-- 조건 일련번호
	CND_SN SERIAL NOT NULL,
	-- 평가 항목 구분
	EVL_ITM_SE VARCHAR(50),
	-- 평가 항목 명
	EVL_ITM_NM VARCHAR(200),
	-- 평가 항목 코드
	EVL_ITM_CD VARCHAR(20),
	-- 평가 목적
	EVL_OBJTV VARCHAR(200),
	-- 관종 코드
	MTRPIPE_CD VARCHAR(20),
	-- 범위 시작 값
	RANG_BEGIN_VAL NUMERIC,
	-- 범위 종료 값
	RANG_END_VAL NUMERIC,
	-- 범위 종료 포함 여부
	RANG_END_INCS_YN CHAR(1),
	-- 평가 보기 내용
	EVL_EXPE_CN VARCHAR(1000),
	-- 노후도 점수
	TMWR_SCOR NUMERIC,
	CONSTRAINT pk_t_inev_cnd PRIMARY KEY (CND_SN)
) WITHOUT OIDS;


-- 간접평가상태등급 : 간접평가상태등급
CREATE TABLE T_INEV_GRAD
(
	-- 관종 코드
	MTRPIPE_CD VARCHAR(20) NOT NULL,
	-- 등급 일련번호
	GRAD_SN SERIAL NOT NULL,
	-- 범위 시작 값
	RANG_BEGIN_VAL NUMERIC,
	-- 범위 종료 값
	RANG_END_VAL NUMERIC,
	-- 개량 방안 내용
	IMPVT_MESR_CN VARCHAR(1000),
	CONSTRAINT pk_t_inev_grad PRIMARY KEY (MTRPIPE_CD, GRAD_SN)
) WITHOUT OIDS;


-- 간접평가 매설년수 보정
CREATE TABLE T_INEV_LYYY_REVISN
(
	-- 매설 년수 일련번호
	LYNG_YYNU_SN SERIAL NOT NULL,
	-- 범위 시작 값
	RANG_BEGIN_VAL NUMERIC,
	-- 범위 종료 값
	RANG_END_VAL NUMERIC,
	-- 보정 계수
	REVISN_COEF NUMERIC,
	CONSTRAINT pk_t_inev_lyyy_revisn PRIMARY KEY (LYNG_YYNU_SN)
) WITHOUT OIDS;


-- 간접평가 마스터
CREATE TABLE T_INEV_M
(
	-- 평가 일련번호
	EVL_SN SERIAL NOT NULL,
	-- 평가 일
	EVL_YMD CHAR(8),
	-- 평가 종류
	EVL_KND VARCHAR(5),
	CONSTRAINT pk_t_inev_m PRIMARY KEY (EVL_SN)
) WITHOUT OIDS;


-- 간접평가 가중치
CREATE TABLE T_INEV_WGHT
(
	-- 평가 항목 코드
	EVL_ITM_CD VARCHAR(20) NOT NULL,
	-- 관종 코드
	MTRPIPE_CD VARCHAR(20) NOT NULL,
	-- 평가 항목 구분
	EVL_ITM_SE VARCHAR(50),
	-- 평가 항목 명
	EVL_ITM_NM VARCHAR(200),
	-- 가중치 값
	WGHT_VAL NUMERIC,
	CONSTRAINT pk_t_inev_wght PRIMARY KEY (EVL_ITM_CD, MTRPIPE_CD)
) WITHOUT OIDS;


-- 간접평가 상수관로
CREATE TABLE T_INEV_WTL_PIP
(
	-- 자산 일련번호
	ASST_SN INT NOT NULL,
	-- 평가 일련번호
	EVL_SN INT NOT NULL,
	-- 관리번호
	FTR_IDN VARCHAR(20),
	-- 평가 결과 점수
	EVL_RST_SCOR NUMERIC,
	-- 누수 민원 수
	WTRLK_CVPL_CO NUMERIC,
	-- 이형 관종 수
	HETERO_MTRPIPE_CO NUMERIC,
	-- 가지 밀도
	BRACH_DN NUMERIC,
	-- 수질 부식 정도
	QLTWTR_CRSN_DEG NUMERIC,
	-- 토양 부식 정도
	SOIL_CRSN_DEG NUMERIC,
	-- 최대 수압
	MXMM_PRSRWTR NUMERIC,
	-- 사고 이력 수
	ACDNT_HIST_CO NUMERIC,
	-- 급수 가지 수
	WTRSPL_BRANCH_CO NUMERIC,
	-- 밸브 수
	VALE_CO NUMERIC,
	CONSTRAINT pk_t_inev_wtl_pip PRIMARY KEY (ASST_SN)
) WITHOUT OIDS;



/* Comments */

COMMENT ON TABLE T_AM_WTL_PIP IS '자산 상수관로';
COMMENT ON COLUMN T_AM_WTL_PIP.ASST_SN IS '자산 일련번호';
COMMENT ON COLUMN T_AM_WTL_PIP.FTR_IDN IS '관리번호';
COMMENT ON COLUMN T_AM_WTL_PIP.LBLK_NM IS '대블록 명';
COMMENT ON COLUMN T_AM_WTL_PIP.MBLK_NM IS '중블록 명';
COMMENT ON COLUMN T_AM_WTL_PIP.SBLK_NM IS '소블록 명';
COMMENT ON COLUMN T_AM_WTL_PIP.INSTALL_YMD IS '설치일';
COMMENT ON COLUMN T_AM_WTL_PIP.MTRPIPE_CD IS '관종 코드';
COMMENT ON COLUMN T_AM_WTL_PIP.PIP_DMTR IS '관경';
COMMENT ON COLUMN T_AM_WTL_PIP.PIP_THKNS IS '관두께';
COMMENT ON COLUMN T_AM_WTL_PIP.PIP_LT IS '관길이';
COMMENT ON COLUMN T_AM_WTL_PIP.LWET_DP IS '최저 깊이';
COMMENT ON COLUMN T_AM_WTL_PIP.TOP_DP IS '최고 깊이';
COMMENT ON COLUMN T_AM_WTL_PIP.SOIL_KND IS '토양 종류';
COMMENT ON COLUMN T_AM_WTL_PIP.ELTR_MENS_VAL IS '전기 방식 값';
COMMENT ON COLUMN T_AM_WTL_PIP.ROAD_TY IS '도로 유형';
COMMENT ON TABLE T_INEV_CND IS '간접평가조건 : 간접평가조건';
COMMENT ON COLUMN T_INEV_CND.CND_SN IS '조건 일련번호';
COMMENT ON COLUMN T_INEV_CND.EVL_ITM_SE IS '평가 항목 구분';
COMMENT ON COLUMN T_INEV_CND.EVL_ITM_NM IS '평가 항목 명';
COMMENT ON COLUMN T_INEV_CND.EVL_ITM_CD IS '평가 항목 코드';
COMMENT ON COLUMN T_INEV_CND.EVL_OBJTV IS '평가 목적';
COMMENT ON COLUMN T_INEV_CND.MTRPIPE_CD IS '관종 코드';
COMMENT ON COLUMN T_INEV_CND.RANG_BEGIN_VAL IS '범위 시작 값';
COMMENT ON COLUMN T_INEV_CND.RANG_END_VAL IS '범위 종료 값';
COMMENT ON COLUMN T_INEV_CND.RANG_END_INCS_YN IS '범위 종료 포함 여부';
COMMENT ON COLUMN T_INEV_CND.EVL_EXPE_CN IS '평가 보기 내용';
COMMENT ON COLUMN T_INEV_CND.TMWR_SCOR IS '노후도 점수';
COMMENT ON TABLE T_INEV_GRAD IS '간접평가상태등급 : 간접평가상태등급';
COMMENT ON COLUMN T_INEV_GRAD.MTRPIPE_CD IS '관종 코드';
COMMENT ON COLUMN T_INEV_GRAD.GRAD_SN IS '등급 일련번호';
COMMENT ON COLUMN T_INEV_GRAD.RANG_BEGIN_VAL IS '범위 시작 값';
COMMENT ON COLUMN T_INEV_GRAD.RANG_END_VAL IS '범위 종료 값';
COMMENT ON COLUMN T_INEV_GRAD.IMPVT_MESR_CN IS '개량 방안 내용';
COMMENT ON TABLE T_INEV_LYYY_REVISN IS '간접평가 매설년수 보정';
COMMENT ON COLUMN T_INEV_LYYY_REVISN.LYNG_YYNU_SN IS '매설 년수 일련번호';
COMMENT ON COLUMN T_INEV_LYYY_REVISN.RANG_BEGIN_VAL IS '범위 시작 값';
COMMENT ON COLUMN T_INEV_LYYY_REVISN.RANG_END_VAL IS '범위 종료 값';
COMMENT ON COLUMN T_INEV_LYYY_REVISN.REVISN_COEF IS '보정 계수';
COMMENT ON TABLE T_INEV_M IS '간접평가 마스터';
COMMENT ON COLUMN T_INEV_M.EVL_SN IS '평가 일련번호';
COMMENT ON COLUMN T_INEV_M.EVL_YMD IS '평가 일';
COMMENT ON COLUMN T_INEV_M.EVL_KND IS '평가 종류';
COMMENT ON TABLE T_INEV_WGHT IS '간접평가 가중치';
COMMENT ON COLUMN T_INEV_WGHT.EVL_ITM_CD IS '평가 항목 코드';
COMMENT ON COLUMN T_INEV_WGHT.MTRPIPE_CD IS '관종 코드';
COMMENT ON COLUMN T_INEV_WGHT.EVL_ITM_SE IS '평가 항목 구분';
COMMENT ON COLUMN T_INEV_WGHT.EVL_ITM_NM IS '평가 항목 명';
COMMENT ON COLUMN T_INEV_WGHT.WGHT_VAL IS '가중치 값';
COMMENT ON TABLE T_INEV_WTL_PIP IS '간접평가 상수관로';
COMMENT ON COLUMN T_INEV_WTL_PIP.ASST_SN IS '자산 일련번호';
COMMENT ON COLUMN T_INEV_WTL_PIP.EVL_SN IS '평가 일련번호';
COMMENT ON COLUMN T_INEV_WTL_PIP.FTR_IDN IS '관리번호';
COMMENT ON COLUMN T_INEV_WTL_PIP.EVL_RST_SCOR IS '평가 결과 점수';
COMMENT ON COLUMN T_INEV_WTL_PIP.WTRLK_CVPL_CO IS '누수 민원 수';
COMMENT ON COLUMN T_INEV_WTL_PIP.HETERO_MTRPIPE_CO IS '이형 관종 수';
COMMENT ON COLUMN T_INEV_WTL_PIP.BRACH_DN IS '가지 밀도';
COMMENT ON COLUMN T_INEV_WTL_PIP.QLTWTR_CRSN_DEG IS '수질 부식 정도';
COMMENT ON COLUMN T_INEV_WTL_PIP.SOIL_CRSN_DEG IS '토양 부식 정도';
COMMENT ON COLUMN T_INEV_WTL_PIP.MXMM_PRSRWTR IS '최대 수압';
COMMENT ON COLUMN T_INEV_WTL_PIP.ACDNT_HIST_CO IS '사고 이력 수';
COMMENT ON COLUMN T_INEV_WTL_PIP.WTRSPL_BRANCH_CO IS '급수 가지 수';
COMMENT ON COLUMN T_INEV_WTL_PIP.VALE_CO IS '밸브 수';



